Hw03 mongodb
Daria-Valitskaya/nodejs-homework-rest-api pull request #2
Opened 2021-11-12 20:43 UTC by Daria-Valitskaya

Проверьте пожалуйста

2021-11-12 21:55 UTC, KirillKulakow commented on bin/server.js
> +    app.listen(PORT, () => {
добавь перед app.listen "Successfully connection to MongoDB"

2021-11-12 21:57 UTC, KirillKulakow commented on middlewares/validation.js
> +  const validationMiddleware = (req, _, next) => {
можно использовать замыкания (schema) => (req, _, next) => {}

2021-11-12 21:58 UTC, KirillKulakow commented on models/contact.js
> +      minlenght: 3,
подозреваю что здесь ошибка

2021-11-12 22:00 UTC, KirillKulakow commented on routes/api/contacts.js
> +router.patch("/:contactId/favorite", contactsControllers.updateStatusContact);
добавь валидацию

2021-11-12 22:00 UTC, KirillKulakow requested changes
need fix

2021-11-13 07:35 UTC, Daria-Valitskaya commented on models/contact.js
> +      minlenght: 3,
тут оно и правда не работает, надо наверное было добавлять 2 границы? минимум и максимум?

2021-11-13 10:06 UTC, Daria-Valitskaya commented on models/contact.js
> +      minlenght: 3,
ну тут "великий знаток" английского просто ошибся буквами)

2021-11-13 11:42 UTC, KirillKulakow approved these changes

2021-11-13 14:11 UTC, merged