Hw04 auth
Daria-Valitskaya/nodejs-homework-rest-api pull request #3
Opened 2021-11-22 09:23 UTC by Daria-Valitskaya

Проверьте пожалуйста

2021-11-22 20:43 UTC, KirillKulakow commented on controllers/auth/currentUser.js
> +    if (!req.user) {
лишняя проверка - данную проверку выполняет миддлвара авторизации

2021-11-22 20:45 UTC, KirillKulakow commented on controllers/contacts/listContacts.js
> +    const { page, limit } = req.query;
лучше делать проверку данных параметров на число - чтобы не появилась неожиданная ошибка или крах приложения

2021-11-22 20:47 UTC, KirillKulakow commented on controllers/contacts/updateContactById.js
> +    const result = await Contact.findOneAndUpdate({ contactId, id }, req.body, {
сделай точно такой же поиск и в остальных методах (удаление и чтение) - обделила ты их

П.с. поиск по ид и по ид собственника

2021-11-22 20:47 UTC, KirillKulakow commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(" ");
если сделать запрос на список контактов без авторизации - сломается приложение

2021-11-22 20:48 UTC, KirillKulakow commented on package.json
> +    "bcryptjs": "^2.4.3",
ты точно все пакеты которые здесь установлены - используешь в приложении?

2021-11-22 20:49 UTC, KirillKulakow requested changes
Need some fix

2021-11-22 21:21 UTC, Daria-Valitskaya commented on package.json
> +    "bcryptjs": "^2.4.3",
нет не все, я устанавливала их во время чтения конспекта, и уже в процессе работы поняла что не использовала часть

2021-11-23 19:14 UTC, KirillKulakow commented on controllers/contacts/listContacts.js
> +    const skip = Number(page) * Number(limit) - Number(limit);
`const skip = Number(page) * Number(limit) - Number(limit);`
эту строку лучше перенести после проверки

2021-11-23 19:15 UTC, KirillKulakow commented on package.json
> +    "bcryptjs": "^2.4.3",
лучше удалить - те которые не юзаешь

2021-11-24 20:36 UTC, KirillKulakow approved these changes

2021-11-24 21:03 UTC, merged