done
Daria-Valitskaya/nodejs-homework-rest-api pull request #4
Opened 2021-11-27 13:20 UTC by Daria-Valitskaya

проверьте пожалуйста

2021-11-27 18:14 UTC, KirillKulakow commented on controllers/auth/signUp.js
> +    const avatarURL = gravatar.url(email);
здесь было бы хорошо добавить опцию вывода протокола

2021-11-27 18:22 UTC, KirillKulakow commented on middlewares/upload.js
> +  filename: (req, file, cb) => {
было бы хорошо добавить фильтр на файлы по MIME типу

2021-11-27 18:23 UTC, KirillKulakow requested changes
Need fix

2021-11-28 21:49 UTC, KirillKulakow commented on controllers/auth/updateAvatar.js
> +      const avatar = path.join(
очень хорошо)

2021-11-28 21:49 UTC, KirillKulakow approved these changes

2021-11-29 08:00 UTC, Daria-Valitskaya commented on controllers/auth/updateAvatar.js
> +      const avatar = path.join(
спасибо) ошибки предшественников были учтены)

2021-11-29 08:00 UTC, merged